# Generated by Django 5.0.7 on 2024-07-31 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuiGallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("description", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gui_gallery",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagesGuiGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_1", models.ImageField(upload_to="gallery/imgs/%Y/%m/")),
                ("image_2", models.ImageField(upload_to="gallery/imgs/%Y/%m/")),
                ("image_3", models.ImageField(upload_to="gallery/imgs/%Y/%m/")),
                ("image_4", models.ImageField(upload_to="gallery/imgs/%Y/%m/")),
                (
                    "id_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_gui_gallery",
                        to="gui.guigallery",
                    ),
                ),
            ],
        ),
    ]
