# Generated by Django 5.0.7 on 2024-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gui", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guigallery",
            name="music",
            field=models.FileField(upload_to="galleryMusic/%Y/%m/"),
        ),
    ]
