# Generated by Django 5.0.7 on 2024-07-31 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="facebook_field",
        ),
        migrations.RemoveField(
            model_name="user",
            name="instagram_field",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
